branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: nombreEntorno
    group_suffix: null
environment-defaults:
  MyFirstChat:
    branch: null
    repository: null
global:
  application_name: chat
  branch: null
  default_ec2_keyname: MyFirstChat
  default_platform: Corretto 17
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
